CREATE TYPE user_role AS ENUM (
  'admin',
  'content_creator',
  'compliance_advisor'
);

CREATE TYPE review_status AS ENUM (
  'approved',
  'pending',
  'rejected'
);

CREATE TYPE channel_type AS ENUM (
  'homepage',
  'messenger',
  'sns',
  'other'
);

CREATE TYPE content_category AS ENUM (
  'product_ad',
  'brand_service_ad',
  'information',
  'other'
);

CREATE TYPE business_sector AS ENUM (
  'bank',
  'credit_finance',
  'savings_bank',
  'financial_investment',
  'other'
);

CREATE TYPE product_category AS ENUM (
  'deposit',
  'loan',
  'card_benefit',
  'auto_finance',
  'investment',
  'other'
);

CREATE TYPE language_code AS ENUM (
  'ko',
  'en',
  'fil',
  'km',
  'zh',
  'vi'
);

CREATE TYPE content_type AS ENUM (
  'text',
  'file',
  'file_with_text'
);

CREATE TYPE reference_document_type AS ENUM (
  'law',
  'regulation',
  'guideline',
  'internal_policy',
  'examples',
  'other'
);

CREATE TYPE chat_message_role AS ENUM (
  'user',
  'assistant',
  'system',
  'tool'
);

CREATE TYPE chat_message_content_type AS ENUM (
  'text',
  'json',
  'mixed'
);

CREATE TABLE IF NOT EXISTS teams (
  team_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(20) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role user_role NOT NULL,
  team_id BIGINT NOT NULL REFERENCES teams(team_id) ON UPDATE CASCADE ON DELETE NO ACTION,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS review_boards (
  board_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_creator_id BIGINT NOT NULL REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE NO ACTION,
  compliance_advisor_id BIGINT NOT NULL REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE NO ACTION,
  management_number VARCHAR(50) NOT NULL UNIQUE,
  review_approval_number VARCHAR(50) UNIQUE,
  title VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS review_content_versions (
  content_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_id BIGINT NOT NULL REFERENCES review_boards(board_id) ON UPDATE CASCADE ON DELETE CASCADE,
  version_no INTEGER NOT NULL,
  business_sector business_sector NOT NULL,
  channel_type channel_type NOT NULL,
  content_type content_type NOT NULL,
  content_category content_category NOT NULL,
  product_category product_category,
  language_code language_code NOT NULL,
  content_file_path TEXT,
  content_text TEXT,
  content_description VARCHAR(255),
  review_status review_status NOT NULL DEFAULT 'pending',
  review_comments TEXT,
  review_reports TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  UNIQUE (board_id, version_no)
);

CREATE TABLE IF NOT EXISTS review_content_chunks (
  chunk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_version_id BIGINT NOT NULL REFERENCES review_content_versions(content_version_id) ON UPDATE CASCADE ON DELETE CASCADE,
  chunk_index INTEGER NOT NULL,
  chunk_text TEXT NOT NULL,
  search_text TEXT,
  embedding VECTOR(1024) NOT NULL,
  search_vector TSVECTOR GENERATED ALWAYS AS (
    to_tsvector('simple', coalesce(search_text, ''))
  ) STORED,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (content_version_id, chunk_index)
);

CREATE TABLE IF NOT EXISTS reference_documents (
  document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_type reference_document_type NOT NULL,
  title VARCHAR(255) NOT NULL,
  issuing_authority VARCHAR(255) NOT NULL,
  issued_date DATE,
  source_file_path TEXT NOT NULL,
  CONSTRAINT uq_reference_documents_source_file_path UNIQUE (source_file_path)
);

CREATE TABLE IF NOT EXISTS reference_document_chunks (
  chunk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL REFERENCES reference_documents(document_id) ON UPDATE CASCADE ON DELETE CASCADE,
  chunk_index INTEGER NOT NULL,
  chunk_text TEXT NOT NULL,
  search_text TEXT,
  embedding VECTOR(1024) NOT NULL,
  search_vector TSVECTOR GENERATED ALWAYS AS (
    to_tsvector('simple', coalesce(search_text, ''))
  ) STORED,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (document_id, chunk_index)
);

CREATE TABLE IF NOT EXISTS chat_threads (
  thread_id UUID PRIMARY KEY,
  content_version_id BIGINT NOT NULL REFERENCES review_content_versions(content_version_id) ON UPDATE CASCADE ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE NO ACTION,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_messages (
  message_id UUID PRIMARY KEY,
  thread_id UUID NOT NULL REFERENCES chat_threads(thread_id) ON UPDATE CASCADE ON DELETE CASCADE,
  role chat_message_role NOT NULL,
  content_type chat_message_content_type NOT NULL DEFAULT 'text',
  content_text TEXT,
  content_json JSONB,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_chat_messages_content CHECK (
    (content_type = 'text' AND content_text IS NOT NULL)
    OR (content_type = 'json' AND content_json IS NOT NULL)
    OR (content_type = 'mixed' AND (content_text IS NOT NULL OR content_json IS NOT NULL))
  )
);
