services:
  postgres:
    build:
      context: .
    container_name: jb-data-postgres
    environment:
      POSTGRES_DB: jbdb
      POSTGRES_USER: jbuser
      POSTGRES_PASSWORD: jbpass
    ports:
      - "5432:5432"
    volumes:
      - jb_data_pgdata:/var/lib/postgresql/data

volumes:
  jb_data_pgdata: